# Generated by Django 4.2.20 on 2025-05-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0012_alter_role_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[("normal_user", "Normal User"), ("admin", "Admin")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thriftapp.webuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalBookSource",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                ("source_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("url", models.URLField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_sources",
                        to="thriftapp.listing",
                    ),
                ),
            ],
        ),
    ]
