# Generated by Django 4.2.20 on 2025-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0013_alter_role_role_name_notification_externalbooksource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[("admin", "Admin"), ("normal_user", "Normal User")],
                max_length=20,
            ),
        ),
    ]
