# Generated by Django 4.2.20 on 2025-05-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0016_alter_role_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[("normal_user", "Normal User"), ("admin", "Admin")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PetAdoption",
            fields=[
                ("listing_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("age", models.PositiveIntegerField()),
                ("food_habit", models.CharField(max_length=100)),
                ("potty_trained", models.BooleanField()),
                ("breed", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=6
                    ),
                ),
                ("status", models.CharField(default="available", max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pet_images/"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thriftapp.webuser",
                    ),
                ),
            ],
            options={"db_table": "petadoptiondb",},
        ),
        migrations.CreateModel(
            name="Inbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="thriftapp.webuser",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="thriftapp.webuser",
                    ),
                ),
            ],
        ),
    ]
