# Generated by Django 4.2.20 on 2025-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0024_alter_role_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[("normal_user", "Normal User"), ("admin", "Admin")],
                max_length=20,
            ),
        ),
    ]
